***Variable***
${LocateAmountConfirm}    id=transaction_amount_label
${LocateFeeConfirm}    id=fee_amount_label
${LocateREBATEConfirm}    id=rebate_amount_label
${LocateConfirmButton}    id=confirm_button
${LocateSuccess}    id=result_title_label
${LocateAmountSuccess}    id=amount_label
${LocatePIN}    id=pin_label
${LocateSERIALNO}    id=serial_label
${LocateSucccessBiller}    id=receiver_name_label
${SHARE}    id=SHARE
${CloseSHARE}    id=Close
${BackToHome}    id=back_to_home_button


