***Variable***
${eLoadMainMenu}    //XCUIElementTypeApplication[@name="MSP-UAT"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]
${eLoadHeader}    //XCUIElementTypeNavigationBar[@name="eLoad"]
${eLoadEditMobile}    id=mobile_textfield
${LocateChanneleLoad}    //XCUIElementTypeApplication[@name="MSP-UAT"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText
${eLoad1,000MMK}    id=amount_0_button
${eLoad2,000MMK}   id=amount_1_button
${eLoad3,000MMK}    id=amount_2_button
${eLoad5,000MMK}    id=amount_3_button    
${eLoad10,000MMK}    id=amount_4_button
${eLoad30,000MMK}    id=amount_5_button
${HeadereLoadConfirm}  //XCUIElementTypeStaticText[@name="CONFIRMATION"]
${LocateMenuConfirm}    id=transaction_title_label
${LocaeConfirmeLoadAmount}    id=transaction_amount_label
${eLoadFee}    id=fee_amount_label
${eLoadConfirmRebate}    id=rebate_amount_label
${LocateChanneleLoadConfirm}    id=receiver_name_label
${eLoadConfirmbutton}    id=confirm_button
${eLoadSuccess}    id=result_title_label
${LocateeLoadAmountSuccess}    id=amount_label
${LocateeLoadFeesSuccess}      id=fee_label
${LocateSuccesseLoadSelectMenu}    id=receiver_name_label
${LocateSuccessRebateAmount}    id=rebate_amount_label
${ButtonREDEEM}    xpath=//XCUIElementTypeButton[@name="redeem_button"]
${ButtonTRANSFER_TO_MCDC}    id=donate_button
${SHARE}    id=share_button
${CloseSHARE}    id=Close
${OKButtonTRANSFEROR_LIST}    id=ok_button
${eLoadBackToHome}    xpath=//XCUIElementTypeButton[@name="back_to_home_button"]
${REDEEMSUCCESS}    xpath=//XCUIElementTypeStaticText[@name="Redeem Success"]
${REDEEMRebate}    id=rebate_label
${CloseREDEEMPopup}    id=close_button
${SelectPacketOoredoo}    xpath=//XCUIElementTypeCell[@name="datapack_table_cell"][2]
${SelectPacketMytel}    xpath=//XCUIElementTypeCell[@name="datapack_table_cell"][1]
${Hameload}             //XCUIElementTypeButton[@name="eload_button"]
${Phonebook}            //XCUIElementTypeButton[@name="contact_button"]
${EloadNofrombook}      //XCUIElementTypeStaticText[@name="Myteleload"]
${failedpopup}          //XCUIElementTypeStaticText[@name="message_label"]
${errortext}            //XCUIElementTypeStaticText[@name="description_label"]
${originalerror}        Simulator set up configuration error.
${okbtn}                 //XCUIElementTypeButton[@name="constructive_button"]
${crossbtn}              //XCUIElementTypeButton[@name="close white icon"]
${popupok}            //XCUIElementTypeButton[@name="OK"]
${accesspopup}        //XCUIElementTypeStaticText[@name="“MSP-UAT” Would Like to Access Your Contacts"]


