***Variable***
${Enterpasscodetext}        //XCUIElementTypeStaticText[@value="ENTER PASSCODE"]
${backbtnonpasspage}        //XCUIElementTypeButton[@name="Back"]
${Signinbtn}                //XCUIElementTypeStaticText[@name="Already have an account? SIGN IN"]
${mobilefield}              //*[contains(@value, 'Enter your mobile no.')]
${loginbutton}              //XCUIElementTypeStaticText[@name="SIGN IN"]
${saveerrormsg}             Mobile number not found/Terminated
${errormsg}                 //XCUIElementTypeStaticText[@name="description_label"]
${okerrorpopup}             //XCUIElementTypeButton[@name="constructive_button"]