*** Variable ***
${NRC}         android=UiSelector().text("NRC")
${StateDupli}  android=UiSelector().text("State")
${TAP1NRC}     android=UiSelector().text("1")
${District}    android=UiSelector().text("District")
${AHGAYA}      android=UiSelector().text("AHGAYA")
${dashicon}    android=UiSelector().text("( - )")
${Zone}        android=UiSelector().text("E")
${last_no}     android=UiSelector().text("Last No.")


