*** Variable  ***
${VERIFICATION}    android=UiSelector().text("VERIFICATION")
${VI}              android=UiSelector().text("VERIFY IDENTITY")
${Regsrnam}        id=com.ccpp.msp.uat:id/edt_fname
${passporttab}     id=com.ccpp.msp.uat:id/passport_rb
${Pass_num}        id=com.ccpp.msp.uat:id/edt_id
${RegOk}           android=UiSelector().text("OK")
${Welc_cm}         id=com.ccpp.msp.uat:id/tvWelcomeTo